# For local development (uses Dockerfile.dev, which keeps build deps)

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '1337:1337'
    volumes:
      - .:/app
    links:
      - db
      - sessions
  db:
    image: postgres:12
    ports:
      - '5432:5432'
  sessions:
    image: redis:5
    ports:
      - '6379:6379'

# Documentation: https://docs.docker.com/compose/