version: '3'
services:
  web:
    build: .
    ports:
      - '1337:1337'
    volumes:
      - .:/cppd-medical-report-sails
    links:
      - db
      - sessions
  db:
    image: postgres:12
    ports:
      - '5432:5432'
  sessions:
    image: redis:5
    ports:
      - '6379:6379'

# Documentation: https://docs.docker.com/compose/