name: Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  push_docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
      - name: Get branch
        run: echo ::set-env name=BRANCH::$(echo ${GITHUB_REF:10})
      - name: Build Docker image
        run: docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/cppd-medical-report-sails:${{env.BRANCH}} .
      - name: Publish Docker image
        run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/cppd-medical-report-sails:${{env.BRANCH}}