name: Push Docker Image

# on:
#   push:
#     tags:
#       - '*.*.*'

on: pull_request

jobs:
  push_docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Login to Azure Container Registry
        run: docker login --username ${AZURE_CONTAINER_REGISTRY_USERNAME} --password ${AZURE_CONTAINER_REGISTRY_PASSWORD}
      - name: Build Docker image
        run: docker build -t ${AZURE_CONTAINER_REGISTRY_URL}/cppd-medical-report-sails:${github.ref} .
      - name: Publish Docker image
        run: docker push ${AZURE_CONTAINER_REGISTRY_URL}/cppd-medical-report-sails:${github.ref}