name: Push Docker Image

# on:
#   push:
#     tags:
#       - '*.*.*'

on: pull_request

jobs:
  push_docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
      - name: Build Docker image
        # run: docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/cppd-medical-report-sails:${{github.ref}} .
        run: docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/cppd-medical-report-sails:pr_test .
      - name: Publish Docker image
        # run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/cppd-medical-report-sails:${{ github.ref }}
        run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/cppd-medical-report-sails:pr_test