name: Run Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1

      - name: Install dependencies
        run: npm install

      - name: Linty McLinterson
        run: npm run lint

      - name: Run Cypress end-to-end
        uses: cypress-io/github-action@v1
        env:
          NODE_ENV: testing
        with:
          install: false
          start: npm run start:test
